services:
  app:
    build: 
      context: .
      dockerfile: containers/app.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./:/src:ro
    environment:
      DATABASE_URL: postgresql://test:test@db:5432/books
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: books
volumes:
  postgres_data: